name: 'zentara'

services:
  sveltekit:
    build:
      context: .
      dockerfile: 'Dockerfile'
      args:
        ORIGIN: ${ORIGIN}
    image: ghcr.io/moritzloewenstein/zentara/zentara:latest
    ports:
      - '${PORT}:3000'
    volumes:
      - zentara_data:/app/data

volumes:
  zentara_data:
