name: PR Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: volta-cli/action@v4

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci

      - name: Run check
        run: npm run check

      - name: Run lint
        run: npm run lint

      #- name: Run integration tests
      #  run: |
      #    npx playwright install
      #    npm run test:integration

      #- name: Run unit tests
      #  run: npm run test:unit
