name: CI

on:
  push:
  pull_request:
    branches: [main]

jobs:
  check:
    uses: ./.github/workflows/check.yml
    secrets: inherit
    concurrency:
      group: commit-check-${{ github.head_ref || github.ref }}
      cancel-in-progress: true

  release:
    needs: check
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/ghcr-release.yml
    secrets: inherit
    concurrency:
      group: docker-build
      cancel-in-progress: false